=== duythi3n/xml_bt/xsd/drinkshop.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="drink_shop">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="drinks">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="drink">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="id" type="xs:ID"/>
                    <xs:element name="name" type="xs:string"/>
                    <xs:element name="price" type="xs:double"/>
                    <xs:element name="description" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
          <xs:key name="drink_key">
            <xs:selector xpath="drink"/>
            <xs:field xpath="id"/>
          </xs:key>
        </xs:element>
        <xs:element name="customers">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="customer">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="id" type="xs:ID"/>
                    <xs:element name="name" type="xs:string"/>
                    <xs:element name="phone" type="xs:string"/>
                    <xs:element name="email" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
          <xs:key name="customer">
            <xs:selector xpath="customer"/>
            <xs:field xpath="id"/>
          </xs:key>
        </xs:element>
        <xs:element name="orders">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="order">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="id" type="xs:ID"/>
                    <xs:element name="customer_id" type="xs:IDREF"/>
                    <xs:element name="drink_id" type="xs:IDREF"/>
                    <xs:element name="quantity" type="xs:unsignedByte"/>
                    <xs:element name="date">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:pattern
                            value="(0[0-9]{1}|1[0-9]{1}|2[0-9]{1}|3[0-1]{1})-(0[0-9]{1}|1[0-2]{1})-[1-2][0-9]{3}"
                          />
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="status">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="Chưa thanh toán"/>
                          <xs:enumeration value="Đã thanh toán"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
          <xs:key name="order_key">
            <xs:selector xpath="order"/>
            <xs:field xpath="id"/>
          </xs:key>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== duythi3n/xml_bt/xsd/drinkshop_xsd.xml
<?xml version="1.0" encoding="UTF-8"?>

<drink_shop xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="drinkshop.xsd">
  <drinks>
    <drink>
      <id>D001</id>
      <name>Cà phê đen</name>
      <price>20000</price>
      <description>Đồ uống ngon từ hạt cà phê Arabica thuần chất</description>
    </drink>
    <drink>
      <id>D002</id>
      <name>Trà sữa trân châu đường đen</name>
      <price>35000</price>
      <description>Đồ uống trà sữa ngon với trân châu và đường đen thơm ngon</description>
    </drink>
    <drink>
      <id>D003</id>
      <name>Sinh tố dâu</name>
      <price>40000</price>
      <description>Đồ uống sinh tố hoa quả ngon từ dâu tây</description>
    </drink>
  </drinks>

  <customers>
    <customer>
      <id>C001</id>
      <name>Nguyễn Văn A</name>
      <phone>0901234567</phone>
      <email>nguyenvana@gmail.com</email>
    </customer>
    <customer>
      <id>C002</id>
      <name>Trần Thị B</name>
      <phone>0912345678</phone>
      <email>tranthib@gmail.com</email>
    </customer>
  </customers>

  <orders>
    <order>
      <id>O001</id>
      <customer_id>C001</customer_id>
      <drink_id>D001</drink_id>
      <quantity>2</quantity>
      <date>31-03-2023</date>
      <status>Đã thanh toán</status>
    </order>
    <order>
      <id>O002</id>
      <customer_id>C002</customer_id>
      <drink_id>D002</drink_id>
      <quantity>1</quantity>
      <date>14-01-2023</date>
      <status>Chưa thanh toán</status>
    </order>
  </orders>
</drink_shop>
